version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-bank_db}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-bank_db}
      - DB_SSLMODE=disable
      - ENV=${ENV:-development}
    depends_on:
      postgres:
        condition: service_healthy
    command: ["serve", "--host", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped
    volumes:
      - api_logs:/app/logs
    networks:
      - app_network

volumes:
  postgres_data:
  api_logs:

networks:
  app_network:
    driver: bridge
